#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
echo "running gofmt"

out=`git diff master --cached --name-only | grep -v /vendor/ | awk '{print $1}' | egrep ".go$" | xargs gofmt -w -s`
exitcode=0
if [ -n "$out" ]; then
    echo "$out" >&2
    exitcode=1
fi

git diff --cached --name-only | awk '{print $1}' | egrep ".go$" | xargs git add 
exit $exitcode
