#!/bin/sh

set -e

if [ -z "$1" ]
    then
        echo "no job repo provided"
        exit 1
fi

if [ -z "$2" ]
    then
        echo "no version tag provided"
        exit 1
fi

git checkout master 
git pull 
git submodule update

cd jobs/$1 
git fetch
git checkout $2 && cd ../..
git checkout -b sc/bump-$1-$2 
git add .
git commit --no-verify -m "Bump up $1 to $2" 
git push --set-upstream origin sc/bump-$1-$2
