#!/bin/sh

set -e

usage() {
    
    echo "usage: run from ppn-jobs directory"
    printf "\n\tjobs-pr <package-to-update> <version-tag> [jira-ticket-id]\n"
    printf "example:\n\tjobs-pr ppn-foo-bar v1.1.0\n"
    printf "example with jira ticket id:\n\tjobs-pr ppn-foo-bar v1.1.0 PPN-1234\n"
}

jiraTicket=""
if [ ! -d "jobs" ]; then
    echo "must be ran from the top level of the jobs submodule repo"
    usage
    exit 1
fi

if [ -z "$1" ]
    then
        echo "no job repo provided"
        usage
        exit 1
fi

if [ -z "$2" ]
    then
        echo "no version tag provided"
        usage
        exit 1
fi

if [ -n "$3" ]
    then
        jiraTicket="$3: "
fi

branchName="a1/bump-$1-$2"
git checkout master 
git pull 
git submodule update

cd jobs/"$1"
git fetch
git checkout "$2"
cd ../..
git checkout -b "$branchName"
git add .
commitMessage=${jiraTicket}"Bump $branchName"
git commit --no-verify -m "$commitMessage" 
git push --set-upstream origin "$branchName"
